### ISSUE TITLE
Return TAD and LDOS in different formats

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/lastdose#2]
# Summary

As a user, I want lastdose to return TAD and LDOS in different formats, including data.frame and list.

# Tests
- tests/testthat/test-lastdose.R
  - lastdose_df
  - lastdose_list

**Comment by barrettk** [comment]
Notes:
1. The `lastdose()` function will append columns called `TAD` and `LDOS` to 
   the input data indicating the time after dose and last dose, respectively.
1. The `lastdose_list()` function will do the same calculations as `lastdose()`, 
   however a list with elements `tad` and `ldos` will be returned.
1. The `lastdose_df()` function will return a data frame with columns `tad`
   and `ldos` with the same definitions as `lastdose_list()`.
