### ISSUE TITLE
Commented dose records are ignored when finding doses

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/lastdose#8]
# Summary

As a user, I want lastdose to ignore commented records when finding doses.

# Tests

- tests/testthat/test-lastdose.R
  - commented records

**Comment by barrettk** [comment]
Notes:
- By default, comments are found when the data frame has a column called `C`and it is character; rows are commented if `C` is not NA and not equal to `.`
  - A warning is issued when a column `C` is found and it is not character when using the default comment finding mechanism
- The user can also pass a logical vector of rows to be considered as comments
  - An error is generated if the length of the logical vector is not equal to the number of rows in the input data set
  - If the comment vector is length 1 it will be recycled to the number of rows in the data frame
- Commented rows are not considered when finding dosing records, including search for first dose
- Commented rows will have `TAD` and `LDOS` filled in just like non-commented rows according to the last non-commented dosing record
